### ISSUE TITLE
folia error itemedit 3.1.5

### ISSUE THREAD

**Issue by xiaoluofa** [emanondev/ItemEdit#18]
[19:35:44 INFO]: [ItemEdit] Enabling ItemEdit v3.1.5
[19:35:44 INFO]: [ItemEdit] Error while loading ItemEdit, disabling it
[19:35:44 WARN]: java.lang.UnsupportedOperationException
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.handle(CraftScheduler.java:533)
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:257)
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244)
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189)
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158)
[19:35:44 WARN]:        at ItemEdit-3.1.5.jar//emanondev.itemedit.UpdateChecker.logUpdates(UpdateChecker.java:48)
[19:35:44 WARN]:        at ItemEdit-3.1.5.jar//emanondev.itemedit.APlugin.onEnable(APlugin.java:194)
[19:35:44 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:35:44 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:35:44 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:35:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652)
[19:35:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563)
[19:35:44 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[19:35:44 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452)
[19:35:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:35:44 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[19:35:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343)
[19:35:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by emanondev** [comment]
sorry, ended up concluding that folia support would bring a lot of additional work and maintenance, which is not something I'm able to provide for the time being

but anyone willing to can fork itemedit
