### ISSUE TITLE
How I can fix that?

### ISSUE THREAD

**Issue by NickThuan** [emanondev/ItemEdit#4]
[16:18:09] [Server thread/WARN]: java.lang.NoClassDefFoundError: io/lumine/mythic/api/drops/IDrop
[16:18:09] [Server thread/WARN]: 	at emanondev.itemedit.ItemEdit.enable(ItemEdit.java:72)
[16:18:09] [Server thread/WARN]: 	at emanondev.itemedit.APlugin.onEnable(APlugin.java:193)
[16:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[16:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[16:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492)
[16:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406)
[16:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554)
[16:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257)
[16:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
[16:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[16:18:09] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:18:09] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.api.drops.IDrop
[16:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[16:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[16:18:09] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:18:09] [Server thread/WARN]: 	... 12 more

**Comment by emanondev** [comment]
is MythicMobs updated?
Can you post ItemEdit and MythicMob version?
